go:
    version: 1.16
    cgo: false
repository:
    path: github.com/coinjinja/geth-exporter
build:
    flags: -a -tags netgo
    ldflags: |
        -s
        -X {{repoPath}}/version.Version={{.Version}}
        -X {{repoPath}}/version.Revision={{.Revision}}
        -X {{repoPath}}/version.Branch={{.Branch}}
        -X {{repoPath}}/version.BuildUser={{user}}@{{host}}
        -X {{repoPath}}/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    prefix: .
    files:
        - LICENSE
        - NOTICE
crossbuild:
    platforms:
        - linux/amd64
        - darwin/amd64
        - darwin/arm64
        - linux/arm64
